import type { AppLanguage } from './types/models';

export const backupContentLabels: Record<AppLanguage, string> = {
  es: 'Datos e historial', ca: 'Dades i historial', en: 'Data and history',
  eu: 'Datuak eta historia', gl: 'Datos e historial'
};

export const backupLabels = {
  es: { title: 'Copia de seguridad', help: 'Guarda o traslada todo tu trabajo de profesor y tutor, incluido el historial, los informes emitidos y la configuración.', export: 'Exportar', restore: 'Restaurar', preview: 'Resumen de la copia', warning: 'Se sustituirán todos los datos actuales por esta copia. Antes se guardará automáticamente una copia de seguridad de tus datos actuales.', confirm: 'Restaurar y sustituir mis datos', cancel: 'Cancelar', saved: 'Copia de seguridad guardada.', restored: 'Copia restaurada. Copia de los datos anteriores:', error: 'No se ha podido completar la operación. Comprueba que la copia es válida y compatible y vuelve a seleccionarla.', counts: 'Cursos · Alumnos · Asignaturas · Informes', date: 'Fecha de la copia', teacher: 'Profesor', file: 'Copia de seguridad de EduTrack' },
  ca: { title: 'Còpia de seguretat', help: 'Desa o trasllada tota la feina de professor i tutor, inclosos l’historial, els informes emesos i la configuració.', export: 'Exportar', restore: 'Restaurar', preview: 'Resum de la còpia', warning: 'Se substituiran totes les dades actuals per aquesta còpia. Abans es desarà automàticament una còpia de seguretat de les dades actuals.', confirm: 'Restaurar i substituir les meves dades', cancel: 'Cancel·lar', saved: 'Còpia de seguretat desada.', restored: 'Còpia restaurada. Còpia de les dades anteriors:', error: 'No s’ha pogut completar l’operació. Comprova que la còpia és vàlida i compatible i torna a seleccionar-la.', counts: 'Cursos · Alumnes · Assignatures · Informes', date: 'Data de la còpia', teacher: 'Professor', file: 'Còpia de seguretat d’EduTrack' },
  en: { title: 'Backup', help: 'Save or transfer all your teacher and tutor work, including history, issued reports and settings.', export: 'Export', restore: 'Restore', preview: 'Backup summary', warning: 'This backup will replace all current data. Your current data will be backed up automatically first.', confirm: 'Restore and replace my data', cancel: 'Cancel', saved: 'Backup saved.', restored: 'Backup restored. Previous data backup:', error: 'The operation could not be completed. Check that the backup is valid and compatible, then select it again.', counts: 'Years · Students · Subjects · Reports', date: 'Backup date', teacher: 'Teacher', file: 'EduTrack backup' },
  eu: { title: 'Segurtasun-kopia', help: 'Gorde edo lekualdatu irakasle eta tutore gisa egindako lan guztia, historia, jaulkitako txostenak eta ezarpenak barne.', export: 'Esportatu', restore: 'Leheneratu', preview: 'Kopiaren laburpena', warning: 'Kopia honek uneko datu guztiak ordeztuko ditu. Aurretik, uneko datuen segurtasun-kopia automatikoki gordeko da.', confirm: 'Leheneratu eta ordeztu nire datuak', cancel: 'Utzi', saved: 'Segurtasun-kopia gorde da.', restored: 'Kopia leheneratu da. Aurreko datuen kopia:', error: 'Ezin izan da eragiketa burutu. Egiaztatu kopia baliozkoa eta bateragarria dela, eta hautatu berriro.', counts: 'Mailak · Ikasleak · Irakasgaiak · Txostenak', date: 'Kopiaren data', teacher: 'Irakaslea', file: 'EduTrack segurtasun-kopia' },
  gl: { title: 'Copia de seguridade', help: 'Garda ou traslada todo o teu traballo de profesor e titor, incluídos o historial, os informes emitidos e a configuración.', export: 'Exportar', restore: 'Restaurar', preview: 'Resumo da copia', warning: 'Substituiranse todos os datos actuais por esta copia. Antes gardarase automaticamente unha copia de seguridade dos datos actuais.', confirm: 'Restaurar e substituír os meus datos', cancel: 'Cancelar', saved: 'Copia de seguridade gardada.', restored: 'Copia restaurada. Copia dos datos anteriores:', error: 'Non se puido completar a operación. Comproba que a copia é válida e compatible e volve seleccionala.', counts: 'Cursos · Alumnos · Materias · Informes', date: 'Data da copia', teacher: 'Profesor', file: 'Copia de seguridade de EduTrack' }
} satisfies Record<AppLanguage, Record<string, string>>;
